Add files via upload

diff --git a/raspi-info-update b/raspi-info-update
--- a/raspi-info-update
+++ b/raspi-info-update
@@ -11,35 +11,51 @@
 #                                                                               #
 # MIT License                                                                   #
 # Copyright (c) 2019-2025 Massimo Pissarello                                    #
-# Permission is hereby granted, free of charge, to any person obtaining a copy  #
-# of this software and associated documentation files (the "Software"), to deal #
-# in the Software without restriction, including without limitation the rights  #
-# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell     #
-# copies of the Software, and to permit persons to whom the Software is         #
-# furnished to do so, subject to the following conditions:                      #
-# The above copyright notice and this permission notice shall be included in    #
-# all copies or substantial portions of the Software.                           #
 #                                                                               #
 #################################################################################
 
 
-RI=raspi-info
-UPVER=$(curl -sSfL https://raw.githubusercontent.com/mapi68/$RI/master/version)
+# Main Variables
+RI="raspi-info"
+UPVER=$(curl -sSfL "https://raw.githubusercontent.com/mapi68/$RI/master/version")
 
+# Installation Function
 install() {
-	echo -e '\e[1;33m'"Installing latest version $UPVER of $RI..."
-	echo -e '\e[0m'
-	wget -nv -P /tmp/ https://github.com/mapi68/"$RI"/raw/master/"$RI"_latest.deb
-	sudo apt install -qq -y /tmp/"$RI"_latest.deb; rm /tmp/"$RI"_latest.deb
+  echo -e "\e[1;33mInstalling latest version $UPVER of $RI...\e[0m"
+  temp_deb="/tmp/${RI}_latest.deb"
+  curl -sSfL "https://github.com/mapi68/$RI/raw/master/${RI}_latest.deb" -o "$temp_deb"
+  if [[ $? -eq 0 ]]; then
+    sudo apt install -qq -y "$temp_deb" && rm "$temp_deb"
+    if [[ $? -eq 0 ]]; then
+      echo -e "\e[1;32mInstallation successful!\e[0m" && echo
+    else
+      echo -e "\e[1;31mInstallation failed.\e[0m" && echo
+      return 1 # Signal an error
+    fi
+  else
+    echo -e "\e[1;31mFailed to download $RI.\e[0m" && echo
+    return 1 # Signal an error
+  fi
 }
 
-if [[ ! -f /usr/bin/$RI ]]; then
-	echo -e '\e[1;33m'"$RI is not installed in your Raspberry Pi"
-	echo -e '\e[0m'
-	exit 1
-elif VER=$(dpkg -s $RI | grep '^Version:' | awk '/:/ {print $2}')
-	[[ "$VER" -ge "$UPVER" ]]; then
-	echo -e '\e[1;32m'"You have latest version $UPVER of $RI: no need update"
-	echo -e '\e[0m'
-else install
+# Check if the program is installed
+if ! command -v "$RI" &> /dev/null; then
+  echo -e "\e[1;33m$RI is not installed on your Raspberry Pi.\e[0m"
+  exit 1
+fi
+
+# Get the installed version
+VER=$(dpkg -s "$RI" 2>/dev/null | awk '/^Version:/ {print $2}')
+
+# Check if the installed version is newer or equal to the remote version
+if [[ "$VER" == "$UPVER" ]]; then
+  echo -e "\e[1;32mYou have the latest version $UPVER of $RI: no update needed.\e[0m" && echo
+  exit 0
+elif [[ "$VER" > "$UPVER" ]]; then
+  echo -e "\e[1;32mYou have a newer version $VER than the remote $UPVER: no update needed.\e[0m" && echo
+  exit 0
+else
+  # Perform installation if the remote version is newer
+  install
+  exit $? # Propagate the exit code of the install function
 fi
